"""initial models

Revision ID: cfd3ccde8159
Revises: 
Create Date: 2025-11-24 10:47:33.503596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd3ccde8159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='dogsize'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('neutered', sa.Boolean(), nullable=False),
    sa.Column('admitted_date', sa.Date(), nullable=False),
    sa.Column('released_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('arrived', 'adopted', 'returned', name='dogstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_id'), 'dogs', ['id'], unique=False)
    op.create_table('dog_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dog_history_id'), 'dog_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dog_history_id'), table_name='dog_history')
    op.drop_table('dog_history')
    op.drop_index(op.f('ix_dogs_id'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
